stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Construction du projet"

job_test:
  stage: test
  script:
    - echo "Tests en cours..."

job_deploy:
  stage: deploy
  script:
    - echo "Déploiement terminé"
