stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Je construis le projet"

job_test:
  stage: test
  script:
    - echo "Je teste le projet"

job_deploy:
  stage: deploy
  script:
    - echo "Je déploie le projet"
